version: '3.8'

services:
  web:
    build: .
    command: gunicorn --bind 0.0.0.0:8000 api.wsgi:application
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    env_file:
      - .env

volumes:
  postgres_data: