name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.9

      - name: Install Docker Compose
        run: sudo apt-get install docker-compose

      - name: Build and run Docker containers
        run: docker-compose up --build -d

      - name: Run tests
        run: docker-compose exec -T web python manage.py test

      - name: Stop Docker containers
        run: docker-compose down